
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Mar 22 08:32:53 CST 2017
//----------------------------------------------------

package org.alejandrohernandez.analizadorHaskell;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int decc = 33;
  public static final int indiceLista = 29;
  public static final int comentariolinea = 51;
  public static final int mod = 16;
  public static final int dosPuntos = 48;
  public static final int masMas = 28;
  public static final int tamanio = 43;
  public static final int par = 40;
  public static final int asc = 41;
  public static final int coma = 4;
  public static final int dollar = 2;
  public static final int calcular = 31;
  public static final int caracter = 56;
  public static final int let = 27;
  public static final int succ = 30;
  public static final int menorIgual = 24;
  public static final int comentarioMultilinea = 50;
  public static final int sum = 36;
  public static final int si = 44;
  public static final int then = 45;
  public static final int max = 35;
  public static final int menos = 13;
  public static final int menor = 22;
  public static final int porcentaje = 32;
  public static final int EOF = 0;
  public static final int aP = 6;
  public static final int mas = 12;
  public static final int revers = 38;
  public static final int mayorIgual = 25;
  public static final int error = 1;
  public static final int aL = 10;
  public static final int mayor = 23;
  public static final int entero = 52;
  public static final int or = 20;
  public static final int pot = 18;
  public static final int por = 14;
  public static final int aC = 8;
  public static final int id = 53;
  public static final int product = 37;
  public static final int sqrt = 17;
  public static final int caso = 47;
  public static final int impr = 39;
  public static final int pC = 3;
  public static final int fin = 49;
  public static final int desc = 42;
  public static final int igualIgual = 21;
  public static final int diferente = 26;
  public static final int and = 19;
  public static final int cP = 7;
  public static final int cL = 11;
  public static final int div = 15;
  public static final int asignacion = 5;
  public static final int min = 34;
  public static final int decimal = 54;
  public static final int cadena = 55;
  public static final int sino = 46;
  public static final int cC = 9;
}

