/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.alejandrohernandez.interfaz;

import java.io.IOException;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.UIManager;
import javax.swing.text.BadLocationException;
import javax.swing.text.Utilities;
import jsyntaxpane.DefaultSyntaxKit;
import org.alejandrohernandez.analizadorHaskell.EjecucionHaskell;
import org.alejandrohernandez.analizadorHaskell.ParserV2;
import org.alejandrohernandez.analizadorHaskell.Scanner;
import org.alejandrohernandez.beans.ArregloHaskell;
import org.alejandrohernandez.beans.Metodo;
import org.alejandrohernandez.beans.Variable;
import org.alejandrohernandez.manejadores.TablaSimbolosHaskell;
//import org.alejandrohernandez.analizador.Scanner;

/**
 *
 * @author oscar
 */
public class VentanaPrincipal extends javax.swing.JFrame implements Runnable {

    private ArrayList<listaTabs> ALlistaTabs;
    private ArrayList<listaTabs> temporal;//-----
    private ArrayList<cuerpo> ALlista;
    private int contadorPestanias;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        temporal = new ArrayList<>();
        ALlista = new ArrayList<>();
        ALlistaTabs = new ArrayList<>();
        contadorPestanias = 1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnEjecutar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtConsola.setColumns(20);
        txtConsola.setRows(5);
        jScrollPane1.setViewportView(txtConsola);

        jLabel1.setText("Consola");

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Crear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEjecutar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnEjecutar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        agregar("Nuevo " + contadorPestanias, "", "");
        contadorPestanias++;
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public static void analizar(String texto) throws IOException, Exception {
        texto = texto.toLowerCase();
        StringReader miReader = new StringReader(texto);
        Scanner scn = new Scanner(miReader);
        ParserV2 par = new ParserV2(scn);
        par.parse();

//        Symbol s = (Symbol) scn.next_token();
//        while (s.sym != 0) {
//            System.out.println("Lexema: " + s.value + "         Token: " + s.sym);
//            s = (Symbol) scn.next_token();
//
//        }
    }
    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        // TODO add your handling code here:
        TablaSimbolosHaskell.getInstancia().limpiarInstancia();
        EjecucionHaskell.resultadoFinalHaskell = "";
        txtConsola.setText("");
        for (int k = 0; k < ALlistaTabs.size(); k++) {

            try {
                // nodo = text.compilar(ALlistaTabs.get(k).panel.getText());
                analizar(ALlistaTabs.get(k).panel.getText());
                txtConsola.setText(txtConsola.getText() + EjecucionHaskell.resultadoFinalHaskell);
            } catch (Exception ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEjecutarActionPerformed
    private void agregar(String nombre, String direc, String texto) {
        JPanel panel;
        JScrollPane barra;
        JEditorPane codigo;
        panel = new JPanel();
        barra = new JScrollPane();
        codigo = new JEditorPane();
        barra.setViewportView(codigo);
        javax.swing.GroupLayout layP = new javax.swing.GroupLayout(panel);
        panel.setLayout(layP);
        layP.setHorizontalGroup(layP.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layP.createSequentialGroup()
                        .addComponent(barra))
        );
        layP.setVerticalGroup(layP.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layP.createSequentialGroup()
                        .addComponent(barra))
        );
        jTabbedPane1.add(nombre, panel);
        DefaultSyntaxKit.initKit();
        codigo.setContentType("text/java");

        codigo.addCaretListener(new javax.swing.event.CaretListener() {
            @Override
            public void caretUpdate(javax.swing.event.CaretEvent eva) {
                texCaretUpdate(eva);
            }
        });
        listaTabs nuevo;
        nuevo = new listaTabs(codigo);
        ALlistaTabs.add(nuevo);
        ALlistaTabs.get(ALlistaTabs.size() - 1).panel.setText(texto);
        cuerpo nue = new cuerpo(nombre, direc);
        ALlista.add(nue);

    }

        public void texCaretUpdate(javax.swing.event.CaretEvent evt) {
            int num = jTabbedPane1.getSelectedIndex();
            try {
                int caretPos = ALlistaTabs.get(num).panel.getCaretPosition();
                int rowNum = (caretPos == 0) ? 1 : 0;
                for (int offset = caretPos; offset > 0;) {
                    offset = Utilities.getRowStart(ALlistaTabs.get(num).panel, offset) - 1;
                    rowNum++;
                }
                int offset = Utilities.getRowStart(ALlistaTabs.get(num).panel, caretPos);
                int colNum = caretPos - offset + 1;
                jLabel1.setText("Linea: " + rowNum + "       Columna: " + colNum);
            } catch (BadLocationException ex) {
                Logger.getLogger(listaTabs.class.getName()).log(Level.SEVERE, null, ex);
            }
            // TODO add your handling code here:
            // TODO add your handling code here:
        }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            // UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            //UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            // UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtConsola;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
