
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Apr 01 23:42:22 CST 2017
//----------------------------------------------------

package org.alejandrohernandez.analizadorgraphik;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int menos = 14;
  public static final int menor = 23;
  public static final int graphikar = 60;
  public static final int punto = 5;
  public static final int importar = 31;
  public static final int div = 16;
  public static final int dosPuntos = 67;
  public static final int mas = 13;
  public static final int cadena = 72;
  public static final int mientras = 56;
  public static final int llamarhk = 51;
  public static final int hereda = 34;
  public static final int imprimir = 61;
  public static final int llamar = 48;
  public static final int privado = 29;
  public static final int menorIgual = 25;
  public static final int sino = 44;
  public static final int procesar = 64;
  public static final int decimal = 69;
  public static final int terminar = 59;
  public static final int caso = 53;
  public static final int interrogacion = 2;
  public static final int tipoCadena = 74;
  public static final int dondetodo = 66;
  public static final int incluirhk = 50;
  public static final int or = 19;
  public static final int caracter = 41;
  public static final int asignacion = 6;
  public static final int nuevo = 35;
  public static final int datos = 62;
  public static final int id = 70;
  public static final int dondecada = 65;
  public static final int mayorIgual = 26;
  public static final int pC = 3;
  public static final int cP = 8;
  public static final int seleccion = 52;
  public static final int cL = 12;
  public static final int menosMenos = 46;
  public static final int protegido = 30;
  public static final int tipoBool = 42;
  public static final int vacio = 38;
  public static final int and = 18;
  public static final int cC = 10;
  public static final int retornar = 47;
  public static final int mayor = 24;
  public static final int xor = 20;
  public static final int tipoDecimal = 40;
  public static final int EOF = 0;
  public static final int inicio = 49;
  public static final int falso = 37;
  public static final int publico = 28;
  public static final int archivogk = 71;
  public static final int verdadero = 36;
  public static final int error = 1;
  public static final int continuar = 58;
  public static final int diferente = 27;
  public static final int si = 43;
  public static final int entero = 68;
  public static final int als = 32;
  public static final int hacer = 57;
  public static final int aP = 7;
  public static final int defecto = 54;
  public static final int donde = 63;
  public static final int pot = 17;
  public static final int aL = 11;
  public static final int tipoCaracter = 73;
  public static final int igualIgual = 22;
  public static final int por = 15;
  public static final int para = 55;
  public static final int tipoEntero = 39;
  public static final int aC = 9;
  public static final int coma = 4;
  public static final int not = 21;
  public static final int var = 33;
  public static final int masMas = 45;
}

